name: Codacy Coverage Reporter

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN  }}
          coverage-reports: cobertura.xml
