name: YELP Detect-Secrets

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  YELP_Detect-Secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Easy detect-secrets
        # You may pin to the exact commit or the version.
        # uses: RobertFischer/detect-secrets-action@fa2d02975bad47bd65e5752377d0ded2714c985f
        uses: RobertFischer/detect-secrets-action@v2.0.0
      
      - name: Commit back .secrets.baseline (if it was missing)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build(detect-secrets): Commit the newly-generated .secrets.baseline file"
