name: TFSec

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tfsec:
    name: TFSec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tfsec_actions_working_dir: "."
          tfsec_output_format: sarif
          tfsec_output_file: tfsec.sarif 
