# exclude-categories: "exclude categories by providing its name"
# exclude-paths: "exclude paths or files from scan"
# exclude-queries: "exclude queries by providing the query ID"
# exclude-results: "exclude results by providing a list of similarity IDs of a result"
log-file: true
# (TRACE,DEBUG,INFO,WARN,ERROR,FATAL) 
log-level: DEBUG
# log-path: path to the log file
silent: false
no-color: false
minimal-ui: true
no-progress: true
# output-path: "./"
# path: "path to file or directory to scan"
# payload-path: "file path to store source internal representation in JSON format"
preview-lines: 30
# queries-path: "path to directory with queries (default ./assets/queries) (default './assets/queries')"
report-formats:
  - json
  - sarif
  - html
# type:
#   - Ansible
#   - CloudFormation
#   - Dockerfile
#   - Kubernetes
#   - Terraform
verbose: true
