trigger: none

pool:
  vmImage: 'ubuntu-latest'

# variables:
#   pathToDockerFile: 'Dockerfile'


stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
  - job: megalinter
    displayName: Mega-Linter
    steps:
    - script: |
        docker pull nvuillam/mega-linter:latest
        docker run --volume $(System.DefaultWorkingDirectory):/tmp/lint nvuillam/mega-linter:latest
      displayName: 'Code Scan using Mega-Linter'
      
    # Publish the Anchore report as an artifact to Azure Pipelines
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: MegaLinter Report'
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/report/'
        ArtifactName: MegaLinterReport
