credentials:
    some_value_here: not_secret
    other_value_here: 1234567890a
    nested:
        value: AKIATESTTESTTESTTEST
        other_value: abcdefghijklmnop
list_of_keys:
    - 123
    - 456
    - 234567890a

test_agent::allowlisted_api_key: 'ToCynx5Se4e2PtoZxEhW7lUJcOX15c54'  # pragma: allowlist secret
low_entropy_binary_secret: !!binary MjNjcnh1IDJieXJpdXYyeXJpaTJidnl1MnI4OXkyb3UwMg==

# this should be ignored as a potential id
allowlisted_id: 'ToCynx5Se4e2PtoZxEhW7lUJcOX15c54'

uuid_should_be_ignored: '203db13e-70c7-462b-9a3d-bf32640cb0be'
