name: AquaSec Trivy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trivy:
    name: AquaSec Trivy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build the Container image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'localbuild/testimage:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'