name: INFRA - IaC - BridgeCrew Checkov

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:        
        directory: "terraform"
        #  check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
        #  skip_check: CKV_AWS_1 # optional: skip a specific check_id. can be comma separated list
        soft_fail: false
        framework: all # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
        output_format: sarif
        quiet: false
        external_checks_dir: ./checkov
        download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
        log_level: DEBUG # optional: set log level. Default WARNING
      env:  
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
#         GITHUB_SERVER_URL: $GITHUB_SERVER_URL
    
    - name: Expose report
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: SARIF results
        path: results.sarif
    
    # Uploads results.sarif to GitHub repository using the upload-sarif action
    - uses: github/codeql-action/upload-sarif@v1
      if: ${{ always() }}
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
