name: INFRA - IaC - Checkmarx IaC KICS

on:
  workflow_dispatch:

jobs:
  checkmarx_kics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create KICS Results Directory
        run: mkdir -p KICSResults

      - name: Run Checkmarx KICS Scan
        uses: checkmarx/kics-action@v1.3
        with:
          path: ./terraform/azure
          platform_type: terraform
          fail_on: medium,high
          output_format: sarif
          output_path: KICSResults
          bom: true
          disable_full_descriptions: false
          disable_secrets: false
          enable_comments: true
          verbose: true

      - name: Display KICS Results
        if: ${{ always() }}
        run: |
          cat KICSResults/results.json

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: KICSResults/results.sarif