name: GitHub Super-Linter

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  github_super_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Super-Linter
        uses: github/super-linter@v3.15.3
