name: QUAL - GitHub Super-Linter

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  github_super_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
