name: SEC - ShiftLeftSecurity Scan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  shift_left_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@v1.3.0
        with:
          type: "credscan,python,nodejs,csharp,terraform,yaml,bash,depscan"
          output: ShiftLeftReport
        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true

      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: ShiftLeftReport

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ShiftLeftReport
