name: INFRA - IaC - TFSec

on:
  workflow_dispatch:

jobs:
  tfsec:
    name: TFSec
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run TFSec scan
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif          

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif   
