name: INFRA - IaC - TFSec

on:
  workflow_dispatch:

jobs:
  tfsec:
    name: TFSec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run TFSec scan
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif    
          working-directory: ./Infrastructure-Source-Code/terraform/azure      

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
