name: INFRA - IaC - Terraform Compliance

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform_compliance:
    runs-on: ubuntu-latest
    name: TerraformCompliance-Action
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    # - name: Terraform Plan
    #   id: plan
    #   run: |
    #     terraform init && terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json
    
    - name: Terraform-Compliance
      uses: terraform-compliance/github_action@main
      with:
        plan: ./Infrastructure-Source-Code/TerraformCompliance-Features/plan.out.json
        features: ./Infrastructure-Source-Code/TerraformCompliance-Features/
