trigger: none
pr: none

pool:
  vmImage: 'windows-latest'


stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
    - job: ARMTTKJob
      displayName: Run Azure Resource Manager (ARM) Template Tool Kit (TTK) Tests
      steps:
      - task: RunARMTTKTests@1
        displayName: Run ARM TTK Tests
        inputs:
          templatelocation: '$(System.DefaultWorkingDirectory)\Infrastructure-Source-Code\ARMTTK-TestFiles'
          resultLocation: '$(System.DefaultWorkingDirectory)\Results'
          # includeTests: 'VM Images Should Use Latest Version,Resources Should Have Location'
          # skipTests: 'VM Images Should Use Latest Version,Resources Should Have Location'
          # mainTemplates: 'template1.json, template2.json'
          allTemplatesMain: true
          cliOutputResults: true

      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: '$(System.DefaultWorkingDirectory)\Results\*-armttk.xml'
        condition: always()
