trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
  - job: GrypeJob
    displayName: Run Grype Scan
    steps:
    # - template: templates/docker-compose-build.yml

    - script: |
        docker image pull docker.io/library/node:19
      displayName: Pull Node Docker Image
    
    - script: |
        docker run --rm \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --name Grype anchore/grype:latest \
            docker.io/library/node:19
      displayName: Run Grype Container Scan
    
    - script: |
        docker run --rm \
          --volume $(System.DefaultWorkingDirectory)/Application-Source-Code:/src \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --name Grype anchore/grype:latest \
            dir:/src
      displayName: Run Grype Directory Scan
      condition: succeededOrFailed()
