trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: MSFTSecureDevOps
  displayName: Microsoft Secure DevOps
  jobs:
  - job: MSFTSecureDevOps
    displayName: Microsoft Secure DevOps
    steps:
    # The CredScan analyzer depends on .NET 3.1.
    - task: UseDotNet@2
      displayName: 'Use dotnet 3.1'
      inputs:
        version: 3.1.x

    - task: UseDotNet@2
      displayName: 'Use dotnet 5.0'
      inputs:
        version: 5.0.x

    # The MicrosoftSecurityDevOps build task depends on .NET 6.
    - task: UseDotNet@2
      displayName: 'Use dotnet 6.0'
      inputs:
        version: 6.0.x

    - task: MicrosoftSecurityDevOps@1
      displayName: 'Run Microsoft Security DevOps'
