trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
  - job: ShiftLeftJob
    displayName: Run ShiftLeft Scan
    steps:
    - script: |
        docker run \
          -e SCAN_DEBUG_MODE=debug \
          --volume "$(Build.SourcesDirectory):/app" \
          --volume "$(Build.ArtifactStagingDirectory):/reports" \
          shiftleft/sast-scan scan --src /app --build \
          --out_dir /reports/CodeAnalysisLogs
      displayName: "Perform ShiftLeft Scan"
      continueOnError: "true"

    - task: PublishBuildArtifacts@1
      displayName: "Publish Analysis Logs"
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs"
        ArtifactName: "CodeAnalysisLogs"
        publishLocation: "Container"
