trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
  - job: YelpDetectSecretsJob
    displayName: Run YELP Detect-Secrets Scan
    steps:
    - task: UsePythonVersion@0
      displayName: "Set Python 3 as default"
      inputs:
        versionSpec: 3

    - task: CmdLine@2
      displayName: "Install detect-secrets using pip"
      inputs:
        script: |
          pip install detect-secrets

    - task: CmdLine@2
      displayName: "Run detect-secrets tool"
      inputs:
        script: |
          detect-secrets scan --all-files --force-use-all-plugins > detect-secrets.json

    - task: PublishPipelineArtifact@1
      displayName: "Publish results in the Pipeline Artifact"
      inputs:
        targetPath: "$(Pipeline.Workspace)/detect-secrets.json"
        artifact: "detect-secrets"
        publishLocation: "pipeline"

    - task: PowerShell@2
      displayName: "Analyzing detect-secrets results"
      condition: always()
      inputs:
        targetType: "inline"
        script: |
          $ds = Get-Content detect-secrets.json
          Write-Output $ds

          $dsObj = $ds | ConvertFrom-Json
          $num = ($dsObj.results | Get-Member -MemberType NoteProperty).Count

          if ($num -gt 0) {
            Write-Host "##vso[task.logissue type=error]Secrets were detected in code."
            exit 1
          }
          else {
            Write-Host "No secrets detected."
          }
        pwsh: true
