trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
    - job: SnykJob
      displayName: Run Snyk Security Scan
      steps:
      # - task: SnykSecurityScan@0
      #   displayName: Snyk Security Scan
      #   inputs:
      #     serviceConnectionEndpoint: 'Snyk-DevSecOps'
      #     testType: 'app'
      #     monitorOnBuild: true
      #     failOnIssues: false
      #     projectName: 'DevSecOpsDemo'
      #     organization: 'AErmie'

      - task: SnykSecurityScan@0
        inputs:
          serviceConnectionEndpoint: 'Snyk-DevSecOps'
          testType: 'container'
          dockerImageName: 'eshoponweb:latest'
          dockerfilePath: '.\'
          monitorOnBuild: true
          failOnIssues: true
          projectName: 'DevSecOpsDemo'
          organization: 'AErmie'