trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SecureVariables


stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
    - job: SonarCloudJob
      displayName: Run SonarCloud Scan
      steps:
      
