trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: SecretScan
  displayName: Scan for Secrets
  jobs:
  - job: TruffleHog
    displayName: Run TruffleHog Secret Scan
    steps:
    - script: |
        docker pull trufflesecurity/trufflehog:latest
      displayName: Pull latest TruffleHog container image

    - script: |
        docker run \
          --rm \
          --volume "$(System.DefaultWorkingDirectory):/pwd" \
          trufflesecurity/trufflehog:latest \
            git \
            https://github.com/AErmie/DevSecOps/ \
            --only-verified
      displayName: Run TruffleHog Secret Scan (GIT)
    
    - script: |
        docker run \
          --rm \
          --volume "$(System.DefaultWorkingDirectory):/pwd" \
          trufflesecurity/trufflehog:latest \
            filesystem \
            /pwd
      displayName: Run TruffleHog Secret Scan (FILESYSTEM)
      condition: succeededOrFailed()
