trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: SecretScan
  displayName: Scan for Secrets
  jobs:
    - job: TruffleHog
      displayName: Run TruffleHog Secret Scan
      steps:
      - bash: | 
          docker pull dxa4481/trufflehog
          docker run --rm --volume $(System.DefaultWorkingDirectory):/src dxa4481/trufflehog --json file:///src > output.json
          cat output.json          
        displayName: TruffleHog Secret Scan Analysis
        # dxa4481/trufflehog
