trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: SecretScan
  displayName: Scan for Secrets
  jobs:
    - job: TruffleHog
      displayName: Run TruffleHog Secret Scan
      steps:
      - bash: | 
          docker pull secfigo/trufflehog
          docker run --rm --volume $(System.DefaultWorkingDirectory):/src secfigo/trufflehog trufflehog --fail_code yes file:///src
        displayName: TruffleHog Secret Scan Analysis
        # dxa4481/trufflehog
